name: Build Python Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Create directory
        run: mkdir -p test/
        shell: bash
    
    
      - name: Create directory
        run: ls -la
        shell: bash
    
      
      - name: Print absolute path of test directory

        run: |

          if [ -d "test" ]; then

            echo "Absolute path of dist directory:"

            realpath test

          else

            echo "dist directory does not exist."

            exit 1

          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-package
          path: test/
          if-no-files-found: error
          retention-days: 5
      - name: List directory contents
        run: ls -la dist/
        shell: bash
     
