name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - master

env:
  CLOUDSMITH_NAMESPACE: ${{ secrets.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
 # PACKAGE_NAME: 'example_package'
  CLOUDSMITH_ACCOUNT: 'your-cloudsmith-account'  # Replace with your Cloudsmith account

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example-package
          path: test
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Request OIDC Token
        id: oidc-token
        run: |
          echo "Requesting OIDC token..."
          OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
          echo "::add-mask::$OIDC_TOKEN"
          echo "::set-output name=oidc-token::$OIDC_TOKEN"

      - name: Request JWT Token from Cloudsmith
        id: jwt-token
        run: |
          echo "Requesting JWT token from Cloudsmith..."
          JWT_RESPONSE=$(curl -X POST "https://api.cloudsmith.io/openid/${{ env.CLOUDSMITH_ACCOUNT }}/" \
            -H "Content-Type: application/json" \
            -d '{"oidc_token": "${{ steps.oidc-token.outputs.oidc-token }}", "service_slug": "${{ env.CLOUDSMITH_SERVICE_SLUG }}"}')
          JWT_TOKEN=$(echo "$JWT_RESPONSE" | jq -r '.token')
          echo "::add-mask::$JWT_TOKEN"
          echo "::set-output name=jwt-token::$JWT_TOKEN"

      - name: Validate JWT Token
        run: |
          JWT_TOKEN=${{ steps.jwt-token.outputs.jwt-token }}
          echo "Validating JWT token..."
          if [ -z "$JWT_TOKEN" ]; then
            echo "JWT token is empty"
            exit 1
          fi
          echo "JWT token is valid"

      - name: Install Cloudsmith CLI
        run: |
          pip install cloudsmith-cli

      - name: Authenticate Cloudsmith CLI
        run: |
          CLOUDSMITH_API_KEY=${{ steps.jwt-token.outputs.jwt-token }}
          echo "Authenticating Cloudsmith CLI..."
          export CLOUDSMITH_API_KEY
      - name: List directory contents
        run: pwd
        shell: bash

      - name: List directory contents
        run: ls -la test/
        shell: bash

      - name: Push package to Cloudsmith
        run: |
          if ! ls test/*.tar.gz 1> /dev/null 2>&1; then
            echo "No package found to upload"
            exit 1
          fi
          cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/*.tar.gz --republish --tags ready-for-production
        shell: bash
